name: Check

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
        - isort
        - flake8
        - bandit
        - readme
        - docs

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install prerequisites
      run: python -m pip install --upgrade setuptools pip wheel tox

    - name: Run ${{ matrix.env }}
      run: tox -e ${{ matrix.env }}
