name: Release

on:
  push:
    tags:
    - '*'

env:
  PIP_DISABLE_PIP_VERSION_CHECK: '1'
  PY_COLORS: '1'

jobs:
  build:
    if: github.repository == 'jazzband/django-analytical'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
          cache-dependency-path: |
            **/pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install tox

      - name: Build package
        run: |
          tox -e package

      - name: Upload packages to Jazzband
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: jazzband
          password: ${{ secrets.JAZZBAND_RELEASE_KEY }}
          repository_url: https://jazzband.co/projects/django-analytical/upload
